function output = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [DESCRIPTION,ED412,ED443,ED488,ED510,ED555,ED665,EDPAR,EDGND,TEMP,DEPTH]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [DESCRIPTION,ED412,ED443,ED488,ED510,ED555,ED665,EDPAR,EDGND,TEMP,DEPTH]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [Description,Ed412,Ed443,Ed488,Ed510,Ed555,Ed665,EdPAR,EdGND,Temp,Depth] = importfile('MAR518_PRR_S01.DAT',14, 561);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/05/11 22:01:55

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 14;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%*s%*s%*s%*s%*s%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow(1)-1, 'WhiteSpace', '', 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    textscan(fileID, '%[^\n\r]', startRow(block)-1, 'WhiteSpace', '', 'ReturnOnError', false);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
output.samplenr = dataArray{:, 1};
output.Ed412 = dataArray{:, 2};
output.Ed443 = dataArray{:, 3};
output.Ed488 = dataArray{:, 4};
output.Ed510 = dataArray{:, 5};
output.Ed555 = dataArray{:, 6};
output.Ed665 = dataArray{:, 7};
output.EdPAR = dataArray{:, 8};
output.EdGND = dataArray{:, 9};
output.t = dataArray{:, 10};
output.d = dataArray{:, 11};


